export const AUTH_USER = 'AUTH_USER';

export const LOGIN = 'LOGIN';
export const REGISTER = 'REGISTER';

export const LOGIN_ERROR = 'LOGIN_ERROR';
export const REGISTER_ERROR = 'REGISTER_ERROR';

export const GET_MOVIES = 'GET_MOVIES';
export const GET_MOVIES_START = 'GET_MOVIES_START';
export const GET_MOVIES_COMLETED = 'GET_MOVIES_COMLETED';

export const GET_MOVIE = 'GET_MOVIE';
export const GET_MOVIE_START = 'GET_MOVIE_START';
export const GET_MOVIE_COMPLETED = 'GET_MOVIE_COMPLETED';

export const SEARCH_MOVIE = 'SEARCH_MOVIE';
export const VOTE_MOVIE = 'VOTE_MOVIE';
export const GET_SIMILAR = 'GET_SIMILAR';
export const CREATE_COMMENT = 'CREATE_COMMENT';
export const REMOVE_ACTIVE = 'REMOVE_ACTIVE';

export const CREATE_MOVIE = 'CREATE_MOVIE';

export const GET_FILTERS = 'GET_FILTERS';
export const TOGGLE_FILTER = 'TOGGLE_FILTER';

export const GET_WATCHLIST = 'GET_WATCHLIST';
export const REMOVE_FROM_WATCHLIST = 'REMOVE_FROM_WATCHLIST';
export const ADD_TO_WATCHLIST = 'ADD_TO_WATCHLIST';
export const SET_WATCHED = 'SET_WATCHED';
export const TOGGLE_SHOW_WATCHED = 'TOGGLE_SHOW_WATCHED';